apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-ui
  labels:
    app: patient-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-ui
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: patient-ui
    spec:
      containers:
      - image: us.icr.io/sn-labs-ayoubchaieb7/patient-ui:v1
        imagePullPolicy: Always
        name: patient-ui
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: 5m
          requests:
            cpu: 2m  
  